import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "Richard",
      email: "admin@example.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: true,
    },
    {
      name: "John",
      email: "user@example.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Echeveria Perle von Nurnberg",
      slug: "ECHEVERIA-PERLE-VON-NURNBERG",
      category: "succulent",
      image: "/images/1.png",
      price: 5.75,
      inStockCount: 10,
      rating: 4.5,
      reviewsCount: 10,
      description:
        "This succulent is a beautifully colored Echeveria Perle Von Nurnberg. The plant is a hybrid of E. Gibbiflora v. Metallica and E. Potosina.",
    },
    {
      name: "String of Pearls",
      slug: "STRING-OF-PEARLS",
      category: "succulent",
      image: "/images/2.png",
      price: 7.75,
      inStockCount: 10,
      rating: 4.8,
      reviewsCount: 16,
      description: `Senecio Rowleyanus has pendant stems to 3' or more with unusual round "leaves" giving the impression of a "String of pearls plant". Both the stems and leaves are green.`,
    },
    {
      name: "Sedum Donkey's Tail",
      slug: "SEDUM-DONKEY'S-TAIL",
      category: "succulent",
      image: "/images/3.png",
      price: 6.75,
      inStockCount: 10,
      rating: 3.5,
      reviewsCount: 20,
      description:
        "Sedum Burrito/ Sedum Morganianum, also known as Burro's Tail or Donkey's Tail Succulent, is native to Mexico.",
    },
    {
      name: "Echeveria Violet Queen",
      slug: "ECHEVERIA-VIOLET-QUEEN",
      category: "succulent",
      image: "/images/4.png",
      price: 6.75,
      inStockCount: 0,
      rating: 3.5,
      reviewsCount: 45,
      description:
        "Echeveria Violet Queen is a charming Echeveria with tips that turn violet-pink in cold weather. The leaves are light grayish green, long, narrow, and curve slightly upward towards the tips similar to that of a lotus blossom.",
    },
    {
      name: "Echeveria Raindrops Succulent",
      slug: "ECHEVERIA-RAINDROPS-SUCCULENT",
      category: "succulent",
      image: "/images/5.png",
      price: 6.75,
      inStockCount: 10,
      rating: 4.5,
      reviewsCount: 20,
      description:
        "Echeveria Raindrops is an unusual succulent that has little globular bumps near the tips of its light green leaves. The bumps and tips of the leaves can turn pink or red in cold weather and bright light.",
    },
    {
      name: "Crassula Morgan Hybrid",
      slug: "CRASSULA-MORGAN-HYBRID",
      category: "succulent",
      image: "/images/6.png",
      price: 6.75,
      inStockCount: 10,
      rating: 4.5,
      reviewsCount: 31,
      description: `This species is a hybrid between Crassula "Morgan Beauty" and Crassula "Springtime""`,
    },
    {
      name: "Aloinopsis Schooneesii",
      slug: "ALOINOPSIS-SCHOONEESII",
      category: "succulent",
      image: "/images/7.png",
      price: 6.75,
      inStockCount: 10,
      rating: 4.5,
      reviewsCount: 42,
      description: `Aloinopsis schooneesii is a South African native succulent. This rare succulent has a pleasing stonelike appearance and vibrant yellow flowering habit`,
    },
    {
      name: "Graptoveria Debbie Succulent",
      slug: "GRAPTOVERIA-DEBBIE-SUCCULENT",
      category: "succulent",
      image: "/images/8.png",
      price: 6.75,
      inStockCount: 10,
      rating: 4.5,
      reviewsCount: 16,
      description: `Graptoveria ‘Debbie’ is an Echeveria hybrid with beautiful rosettes of fleshy gray-purple leaves.`,
    },
    {
      name: "Graptopetalum Superbum",
      slug: "GRAPTOPETALUM-SUPERBUM",
      category: "succulent",
      image: "/images/9.png",
      price: 6.75,
      inStockCount: 10,
      rating: 4.5,
      reviewsCount: 16,
      description: `Graptopetalum Superbum has fleshy pale lavender leaves coated with a layer of white powder, which gives it a lovely pastel look.`,
    },
    {
      name: "variegated-ghost-plant",
      slug: "VARIEGATED GHOST PLANT",
      category: "succulent",
      image: "/images/10.png",
      price: 6.75,
      inStockCount: 10,
      rating: 4.5,
      reviewsCount: 16,
      description: `This listing features our lovely rooted Variegated Graptopetalum paraguayense. This rare beauty is native to Mexico, has blue-gray leaves with some light purple hue and creamy yellow-pink variegation.`,
    },
    {
      name: "Graptosedum California Sunset",
      slug: "GRAPTOSEDUM-CALIFORNIA-SUNSET",
      category: "succulent",
      image: "/images/11.png",
      price: 6.75,
      inStockCount: 10,
      rating: 4.5,
      reviewsCount: 16,
      description: `Graptosedum ‘California Sunset’ is a fun succulent with rosy orange leaves forming small rosettes similar to those of Echeverias.`,
    },
    {
      name: "Echeveria Emerald Ripple",
      slug: "ECHEVERIA-EMERALD-RIPPLE",
      category: "succulent",
      image: "/images/12.png",
      price: 6.75,
      inStockCount: 10,
      rating: 4.5,
      reviewsCount: 16,
      description: `Graptosedum ‘California Sunset’ is a fun succulent with rosy orange leaves forming small rosettes similar to those of Echeverias.`,
    },
  ],
};

export default data;
